#!/bin/bash

# This script is generated by ChatGPT. It could be wrong, incomplete.

# The path to transform, passed as the first argument to the script
path="$1"

# Function to calculate the depth of a path
calculate_depth() {
    local p="$1"
    local depth=0
    while [[ "$p" == */* ]]; do
        ((depth++))
        p="${p#*/}"
    done
    echo "$depth"
}

# Function to format paths exceeding a depth of 2
format_path() {
    local p="$1"
    local depth=$(calculate_depth "$p")
    if [ "$depth" -gt 2 ]; then
        # Extract the last two segments of the path
        local last_two="${p##*/}" # Last segment
        p="${p%/$last_two}" # Remove the last segment from the path
        local second_last="${p##*/}" # Second last segment
        echo "/.../$second_last/$last_two"
    else
        echo "$p"
    fi
}

# Check if the path starts with "~/" or is an absolute path
if [[ "$path" == "$HOME"* ]]; then
    # Path starts with "~/", indicating a path in the user's home directory
    formatted_path="~$(format_path "${path#$HOME}")" # Pass the path without "~/" to the format_path function
elif [[ "$path" == "/"* ]]; then
    # Absolute path
    formatted_path="$(format_path "$path")"
else
    # Relative path, treated as is
    formatted_path="$path"
fi

echo "$formatted_path"
